# Generated by Django 4.2.5 on 2023-09-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
    ]
