# Generated by Django 4.2.5 on 2023-09-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_skills_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
